from __future__ import annotations
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path
from PIL import Image
from .alpha import decontaminate_edges, estimate_corner_background, sanitize_rgba, solid_background_matte

@dataclass
class EngineResult:
    id: str
    label: str
    engine: str
    model: str | None
    status: str
    output_image: Image.Image | None = None
    notes: list[str] = field(default_factory=list)
    error: str | None = None
    def to_manifest_dict(self) -> dict:
        data = asdict(self)
        data.pop("output_image", None)
        return data

def native_alpha_variant(input_image: Image.Image) -> EngineResult:
    if not (input_image.mode in ("RGBA", "LA") or "transparency" in input_image.info):
        return EngineResult("source-alpha-sanitize", "Input alpha sanitized", "native-rgba", None, "skipped", notes=["Input image has no alpha channel."])
    return EngineResult("source-alpha-sanitize", "Input alpha sanitized", "native-rgba", None, "ok", output_image=sanitize_rgba(input_image), notes=["Preserved input alpha channel and cleared hidden RGB below fully transparent pixels."])

def solid_background_variant(input_image: Image.Image, bg_rgb: tuple[int, int, int] | None = None) -> EngineResult:
    try:
        used_bg = bg_rgb or estimate_corner_background(input_image)
        out = solid_background_matte(input_image, used_bg)
        return EngineResult("solid-bg-corner-matte", f"Solid-bg matte ({used_bg[0]},{used_bg[1]},{used_bg[2]})", "pillow-numpy", None, "ok", output_image=out, notes=["Estimated/cut known flat background from corner colour samples.", "Best for images generated on a deliberately flat matte background."])
    except Exception as exc:
        return EngineResult("solid-bg-corner-matte", "Solid-bg matte", "pillow-numpy", None, "failed", error=str(exc))

def rembg_variant(input_path: Path, model: str, decontam_bg: tuple[int, int, int] | None = None, alpha_matting: bool = True) -> EngineResult:
    variant_id = f"rembg-{model}".replace("_", "-")
    try:
        from rembg import new_session, remove
    except Exception as exc:
        return EngineResult(variant_id, f"rembg {model}", "rembg", model, "failed", error=f"rembg is not installed or could not import: {exc}", notes=["Run ./install.sh first."])
    try:
        session = new_session(model)
    except Exception as exc:
        return EngineResult(variant_id, f"rembg {model}", "rembg", model, "failed", error=f"Could not create rembg session for model {model!r}: {exc}")
    try:
        source = Image.open(input_path).convert("RGB")
        kwargs = {"session": session}
        if alpha_matting:
            kwargs.update({"alpha_matting": True, "alpha_matting_foreground_threshold": 240, "alpha_matting_background_threshold": 10, "alpha_matting_erode_size": 10})
        try:
            out = remove(source, **kwargs)
        except TypeError:
            out = remove(source, session=session)
        if not isinstance(out, Image.Image):
            out = Image.open(out).convert("RGBA")
        out = sanitize_rgba(out.convert("RGBA"))
        notes = ["Generated by rembg and saved as RGBA PNG."]
        if decontam_bg is not None:
            out = decontaminate_edges(out, decontam_bg)
            notes.append(f"Semi-transparent edge pixels were cleaned up using edge background RGB {decontam_bg}.")
        return EngineResult(variant_id, f"rembg {model}", "rembg", model, "ok", output_image=out, notes=notes)
    except Exception as exc:
        return EngineResult(variant_id, f"rembg {model}", "rembg", model, "failed", error=str(exc))

def inspyrenet_variant(input_image: Image.Image, mode: str = "base", resize: str = "static") -> EngineResult:
    variant_id = f"inspyrenet-{mode}-{resize}".replace("_", "-")
    try:
        from transparent_background import Remover
    except Exception as exc:
        return EngineResult(variant_id, f"InSPyReNet {mode}/{resize}", "transparent-background", f"{mode}/{resize}", "skipped", error=f"transparent-background is not installed or could not import: {exc}", notes=["Install optional InSPyReNet support with ./install.sh --inspyrenet."])
    try:
        remover = Remover(mode=mode, resize=resize)
        out = remover.process(input_image.convert("RGB"), type="rgba")
        return EngineResult(variant_id, f"InSPyReNet {mode}/{resize}", "transparent-background", f"{mode}/{resize}", "ok", output_image=sanitize_rgba(out.convert("RGBA")), notes=["Generated through transparent-background / InSPyReNet RGBA output."])
    except Exception as exc:
        return EngineResult(variant_id, f"InSPyReNet {mode}/{resize}", "transparent-background", f"{mode}/{resize}", "failed", error=str(exc))

def tool_status() -> dict:
    status = {}
    for module_name in ["PIL", "numpy", "flask", "rembg", "transparent_background"]:
        try:
            module = __import__(module_name)
            status[module_name] = {"available": True, "version": getattr(module, "__version__", None)}
        except Exception as exc:
            status[module_name] = {"available": False, "error": str(exc)}
    status["rembg_cli"] = {"available": shutil.which("rembg") is not None}
    status["linux_save_dialog_helper"] = {"available": any(shutil.which(x) for x in ["zenity", "kdialog", "yad"]), "candidates": {x: shutil.which(x) for x in ["zenity", "kdialog", "yad"]}}
    status["macos_osascript"] = {"available": shutil.which("osascript") is not None}
    return status
